package.json, src/app/index.tsx
This worked to expose the app under "/console", I tested together with https://github.com/infinispan/infinispan/pull/7597
Haven't tested locally though
=> Deploy app to subpath

src/index.html
Resolve js application launch in a sub-route (aka /console/cache/test) in dev env
=> Resolve js application launch in a sub-route

src/app/CacheManagers/CacheManagers.tsx
The key MUST be unique... 
I'm not sure what's really unique here. If nothing is unique in the used object, use the iteration index.
=> React items instanciated from a collection must have a key

package.json
everything is in the commit message =)
=> 'yarn prettier' command to format code, with minimal configuration

src/app/Caches/DetailCache.tsx, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-11490
=> [10.1.x] ISPN-11490 Display cache configuration in the cache detail

src/app/AppLayout/AppLayout.tsx, src/app/Caches/DetailCache.tsx, src/services/cacheService.ts, src/services/utils.ts
https://issues.redhat.com/browse/ISPN-11684
backport #8
=> ISPN-11684 when the creation is not ok, handle errors correctly

src/app/AppLayout/AppLayout.tsx, src/services/cacheService.ts, src/services/utils.ts
https://issues.redhat.com/browse/ISPN-11684
=> [10.1.x] ISPN-11684 Errors not handled correctly when the cache is created

src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/DetailCache.tsx, src/services/displayUtils.ts
Several changes
A warning and prettier code formatter run as well
https://issues.redhat.com/browse/ISPN-11733
=> ISPN-11733 Report UX changes to caches table

src/app/CacheManagers/CacheManagers.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/CacheManagers/TasksTableDisplay.tsx, src/app/app.css, src/services/cacheService.ts, src/services/utils.ts
Depends on #20 
https://issues.redhat.com/browse/ISPN-11494
Issue #12
=> ISPN-11490 delete cache

src/app/CacheManagers/CacheManagers.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/CacheManagers/TasksTableDisplay.tsx, src/services/displayUtils.ts
Fixes
* Tasks and Counters tab count number display
* The label style for counters and tasks type
=> ISPN-11490 Fix tabs count task counter

src/app/AppLayout/AppLayout.tsx, src/app/CacheManagers/CacheManagers.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/CreateCache.tsx, src/app/Common/ActionResponseAlert.tsx, src/app/providers/APIAlertProvider.tsx, src/app/utils/useApiAlert.ts
Fixes cache creation when no config is provided (does not create a local cache anymore)
https://issues.redhat.com/browse/ISPN-11754
Alert error 
* Uses useContext
* Custom hook
* For now, one alert at a time
* Create and Delete refactored
https://issues.redhat.com/browse/ISPN-11705
=> ISPN-11705 Global alert system / ISPN-11754 fix cache creation

src/app/Caches/CacheEntries.tsx, src/app/Caches/ClearAllEntries.tsx, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-11500
#18
=> ISPN-11500 Clear all

src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/CacheEntries.tsx, src/app/Caches/DeleteEntry.tsx, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-11499
https://github.com/infinispan/infinispan-console/issues/17
=> ISPN-11499 Delete entry

src/app/AppLayout/AppLayout.tsx, src/app/routes.tsx
https://issues.redhat.com/browse/ISPN-11786
=> ISPN-11786 Fix menu nav selected

src/app/AppLayout/AppLayout.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/CacheManagers/TasksTableDisplay.tsx, src/app/Caches/AddEntryForm.tsx, src/app/Caches/CacheConfiguration.tsx, src/app/Caches/CacheEntries.tsx, src/app/Caches/ClearAllEntries.tsx, src/app/Caches/DeleteEntry.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/DetailConfigurations.tsx, src/app/Caches/RecentActivityTable.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/providers/RecentActivityContextProvider.tsx, src/app/utils/useRecentActivity.ts, src/services/cacheService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-11762
=> ISPN-11762 Local activity table

package.json, src/app/AppLayout/AppLayout.tsx, src/app/Caches/CacheEntries.tsx, src/app/Caches/CreateOrUpdateEntryForm.tsx, src/app/routes.tsx, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-11498
#16
=> ISPN-11498 Edit entry

src/app/AppLayout/AppLayout.tsx, src/app/Caches/CacheEntries.tsx, src/app/Caches/ClearAllEntries.tsx, src/app/Caches/CreateCache.tsx, src/app/Caches/CreateOrUpdateEntryForm.tsx, src/app/Caches/DeleteEntry.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/DetailConfigurations.tsx, src/app/Caches/RecentActivityTable.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/Common/DataContainerBreadcrumb.tsx, src/app/providers/RecentActivityContextProvider.tsx, src/types/InfinispanTypes.ts
* Activity table 10/cache
* Change links and breadcrumb not to reload the app
New PR added in the issue
https://issues.redhat.com/browse/ISPN-11762
=> ISPN-11762 Local activity table per cache

src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/DetailCache.tsx, src/app/routes.tsx, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-11821
=> ISPN-11821 Land correctly into detail cache

src/app/CacheManagers/CacheManagers.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/Common/TableErrorState.tsx, src/app/GlobalStats/GlobalStats.tsx, src/services/dataContainerService.ts
Run the app without any server and check the console
https://issues.redhat.com/browse/ISPN-11766
=> ISPN-11766 Fix when the server is down

src/app/CacheManagers/CacheTableDisplay.tsx, src/app/CacheManagers/DeleteCache.tsx, src/app/CacheManagers/IgnoreCache.tsx, src/services/cacheService.ts, src/services/dataContainerService.ts
To make this work, we need the PR of the server in, and then use the master
Infinispan REST API PR: https://github.com/infinispan/infinispan/pull/8301
https://issues.redhat.com/browse/ISPN-11667
=> Ignore cache

package.json, src/app/CacheManagers/ProtobufSchemasDisplay.tsx, src/app/Caches/CacheConfiguration.tsx, src/app/Caches/CacheEntries.tsx, src/app/Caches/CacheMetrics.tsx, src/app/Caches/CreateOrUpdateEntryForm.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/QueryEntries.tsx, src/app/Caches/RecentActivityTable.tsx, src/app/Common/TableErrorState.tsx, src/services/cacheService.ts, src/services/displayUtils.ts, src/services/formUtils.ts, src/services/utils.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-11652
=> ISPN-11652 Query values

src/app/IndexManagement/IndexManagement.tsx, src/app/IndexManagement/PurgeIndex.tsx, src/services/cacheService.ts
Depends of https://github.com/infinispan/infinispan-console/pull/48
Don't merge before the PR
https://issues.redhat.com/browse/ISPN-11657
=> ISPN-11657 Purge index

src/app/Caches/DetailCache.tsx, src/app/IndexManagement/IndexManagement.tsx, src/app/IndexManagement/Reindex.tsx, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-11656
=> ISPN-11656 Reindex

src/app/Caches/CreateCache.tsx
Arrive directly to create cache works now
=> fix create cache like cache detail for location

data/docker-compose.yaml, data/infinispan-console.xml, data/xsiteCache.xml, src/app/CacheManagers/CacheManagers.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/DetailCache.tsx, src/app/Common/TableEmptyState.tsx, src/app/XSite/StateTransfer.tsx, src/app/XSite/XSiteCache.tsx, src/app/routes.tsx, src/services/cacheService.ts, src/services/crossSiteReplicationService.ts, src/services/displayUtils.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-11669
https://issues.redhat.com/browse/ISPN-11670
https://issues.redhat.com/browse/ISPN-11671
https://issues.redhat.com/browse/ISPN-11672
=> Xite replication for a cache

pom.xml
https://issues.redhat.com/browse/ISPN-12001
=> ISPN-12001 Add jboss-parent

data/docker-compose.yaml, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/Counters/DeleteCounter.tsx, src/services/authService.ts, src/services/cacheService.ts, src/services/countersService.ts, src/services/displayUtils.ts, src/services/keycloakService.ts, src/services/utils.ts
https://issues.redhat.com/browse/ISPN-12084
depends on #59
=> Ispn 12084 remove counter

src/app/CacheManagers/ProtobufSchemasDisplay.tsx, src/services/protobufService.ts
https://issues.redhat.com/browse/ISPN-12137
=> ISPN-12137 Fix protobuf display

src/app/CacheManagers/ProtobufSchemasDisplay.tsx, src/services/protobufService.ts
https://issues.redhat.com/browse/ISPN-12137
=> [11.x] ISPN-12137 Fix protobuf display

src/app/About/About.tsx, src/app/AppLayout/AppLayout.tsx, src/services/serverService.ts
Just a PR that I wanted to do since a long time 
https://issues.redhat.com/browse/ISPN-12195
=> ISPN-12195 About page for Infinispan Console

src/app/CacheManagers/CacheManagers.tsx, src/app/Caches/CreateCache.tsx, src/app/Caches/DetailCache.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/Common/Health.tsx, src/app/Common/Status.tsx, src/app/IndexManagement/IndexManagement.tsx, src/app/XSite/XSiteCache.tsx, src/app/routes.tsx, src/services/countersService.ts, src/services/protobufService.ts
* take url params from props
* align page headers correctly
* run formatter
=> minor refactor

src/app/CacheManagers/DeleteCache.tsx, src/app/CacheManagers/DeleteSchema.tsx, src/app/Caches/RecentActivityTable.tsx, src/app/providers/RecentActivityContextProvider.tsx, src/app/utils/useRecentActivity.ts
https://issues.redhat.com/browse/ISPN-12161
=> ISPN-12161 clean recent activity table

src/services/authService.ts
https://issues.redhat.com/browse/ISPN-12054
=> ISPN-12054 Replace deprecated REST call

src/app/Caches/CreateCache.tsx
Merge #69 first
https://issues.redhat.com/browse/ISPN-12264
=> ISPN-12264 Fix cache creation

src/app/Caches/Configuration/DetailConfigurations.tsx
To test go directly to http://localhost:9000/console/container/default/configurations/
The app should load correctly
https://issues.redhat.com/browse/ISPN-12200
=> ISPN-12200 Fix the landing into cache configuration templates page

src/app/CacheManagers/DeleteCache.tsx, src/app/CacheManagers/DeleteSchema.tsx, src/app/Caches/RecentActivityTable.tsx, src/app/providers/RecentActivityContextProvider.tsx, src/app/utils/useRecentActivity.ts
=> [11.x] ISPN-12161 clean recent activity table

src/app/CacheManagers/ProtobufSchemasDisplay.tsx, src/app/Common/TableEmptyState.tsx, src/app/app.css
https://issues.redhat.com/browse/ISPN-12310
=> [11.x] ISPN-12310 Backport protobuf fixes

src/app/Common/TableEmptyState.tsx, src/app/ProtoSchema/ProtobufSchemasDisplay.tsx, src/app/app.css
Highlight the code 
https://issues.redhat.com/browse/ISPN-12298
Improve message display
https://issues.redhat.com/browse/ISPN-12310
=> ISPN-12298 and ISPN-12310 Protobuf usability improvements

LICENSE, package.json, pom.xml, src/main/resources/licenses/build.xml
* and store it in the jar
https://issues.redhat.com/browse/ISPN-12329
=> ISPN-12329 Create licenses.xml with console dependencies

LICENSE, package.json, pom.xml, src/main/resources/licenses/build.xml
* and store it in the jar
https://issues.redhat.com/browse/ISPN-12329
=> [11.0.x] ISPN-12329 Create licenses.xml with console dependencies

src/app/Caches/CacheMetrics.tsx, src/app/GlobalStats/GlobalStats.tsx
https://issues.redhat.com/browse/ISPN-12311
backport #80
=> ISPN-12311 Fix data access % in chart

src/app/CacheManagers/CacheManagers.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/DetailCache.tsx, src/app/IndexManagement/IndexManagement.tsx, src/app/IndexManagement/PurgeIndex.tsx, src/app/IndexManagement/Reindex.tsx, src/app/XSite/XSiteCache.tsx, src/services/cacheService.ts, src/services/countersService.ts, src/services/crossSiteReplicationService.ts, src/services/utils.ts
https://issues.redhat.com/browse/ISPN-11324
=> ISPN-11324 Fix caches manipulation with special characters in names

data/docker-compose.yaml, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/DetailCache.tsx, src/app/Common/DataContainerBreadcrumb.tsx, src/app/IndexManagement/IndexManagement.tsx, src/app/XSite/XSiteCache.tsx, src/app/routes.tsx, src/services/cacheService.ts, src/services/crossSiteReplicationService.ts
https://issues.redhat.com/browse/JDG-3494
=> [11.x] ISPN-11324 Fix caches manipulation with special characters in names

package.json
https://issues.redhat.com/browse/ISPN-12361
=> ISPN-12361 Upgrade patternfly version

src/app/Common/DataContainerBreadcrumb.tsx
small non blocking change forgotten
=> ISPN-11324 Breadcumb component

src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/DetailCache.tsx, src/app/Common/Health.tsx, src/app/app.css, src/services/displayUtils.ts
https://issues.redhat.com/browse/ISPN-12376
=> [11.x] ISPN-12376 Deal with Failed health in the console

src/app/CacheManagers/CacheManagers.tsx, src/app/CacheManagers/CacheMangerPage.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/Configuration/DetailConfigurations.tsx, src/app/Caches/CreateCache.tsx, src/app/Caches/DeleteCache.tsx, src/app/Caches/IgnoreCache.tsx, src/app/providers/CacheManagerContextProvider.tsx, src/app/routes.tsx, src/app/services/dataContainerHooks.ts, src/app/services/statsHook.ts, src/services/dataContainerService.ts, src/services/utils.ts
https://issues.redhat.com/browse/ISPN-12433
=> ISPN-12433 Fix delete cache latest page

src/__tests__/views/NotFound.test.tsx, src/__tests__/views/Support.test.tsx, src/app/NotFound/NotFound.tsx, src/app/assets/languages/en.json, src/i18n4Test.js, src/test-utils.tsx
https://issues.redhat.com/browse/ISPN-12445
The PR covers a unit test that mocks and tests the history button click and an override for testing of the languages translation, which is useful to be used on tests and verify labels are correctly externalised into the languages file
=> ISPN-12445 404 small design improvement and unit test

package.json
https://issues.redhat.com/browse/ISPN-12488
=> ISPN-12488 Upgrade to 2020.14 Patternfly

.gitignore, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/CacheManagers/ProtobufSchemasDisplay.tsx, src/services/protobufService.ts
https://issues.redhat.com/browse/ISPN-12506
=> [11.x] ISPN-12506 Fix protobuf schema lack of permission

src/services/utils.ts
@karesti please review and merge when possible
=> Able to customize Infinispan server URL in DevMode

src/__tests__/services/utils.test.ts, src/app/Caches/Entries/CacheEntries.tsx, src/services/cacheService.ts, src/services/utils.ts
https://issues.redhat.com/browse/ISPN-12610
=> ISPN-12610 Protobuf data manipulation fix

package.json
https://issues.redhat.com/browse/ISPN-12613
=> ISPN-12613 Upgrade patternfly to release 2020.16

src/app/providers/CacheDetailProvider.tsx, src/services/cacheService.ts, src/services/utils.ts
https://issues.redhat.com/browse/ISPN-12640
=> ISPN-12640 Deal with server error in getEntries

src/app/Caches/Entries/CacheEntries.tsx
https://issues.redhat.com/browse/ISPN-12654
=> ISPN-12654 Fix getentry for protobuf caches

README.md, pom.xml
https://issues.redhat.com/browse/ISPN-12660
=> ISPN-12660 skipTests property for local build

pom.xml, src/main/resources/licenses/build.xml
https://issues.redhat.com/browse/ISPN-12661
=> [11.0.x] ISPN-12661 Licenses are not properly generated

pom.xml, src/main/resources/licenses/build.xml
https://issues.redhat.com/browse/ISPN-12661
=> ISPN-12661 Licenses are not properly generated

src/app/Caches/Entries/CacheEntries.tsx, src/services/cacheService.ts, src/services/utils.ts
https://issues.redhat.com/browse/ISPN-12719
=> ISPN-12719 Fix json not protobuf parser

src/app/Caches/Entries/CacheEntries.tsx, src/services/cacheService.ts, src/services/utils.ts
https://issues.redhat.com/browse/ISPN-12719
=> [12.0.x]ISPN-12719 Fix json not protobuf parser

data/indexed.json, data/people.proto, package.json, src/app/Caches/CacheMetrics.tsx, src/app/GlobalStats/GlobalStats.tsx, src/services/displayUtils.ts
https://issues.redhat.com/browse/ISPN-12749
closes #123
=> ISPN-12749 Fix pie chart

data/indexed.json, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/DetailCache.tsx, src/services/securityService.ts
https://issues.redhat.com/browse/ISPN-12885
=> ISPN-12885 Monitor right

cypress/integration/cluster-membership-spec.js, cypress/integration/cluster-welcome-spec.js, cypress/integration/global-stats-spec.js, package.json, src/__tests__/views/GlobalStats.test.tsx, src/app/Caches/CacheMetrics.tsx, src/app/Caches/CreateCache.tsx, src/app/Caches/DeleteCache.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/IgnoreCache.tsx, src/app/Caches/Query/QueryEntries.tsx, src/app/Caches/Query/QueryMetrics.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/Counters/DeleteCounter.tsx, src/app/GlobalStats/GlobalStats.tsx, src/app/IndexManagement/IndexManagement.tsx, src/app/IndexManagement/PurgeIndex.tsx, src/app/IndexManagement/Reindex.tsx, src/app/ProtoSchema/CreateProtoSchema.tsx, src/app/ProtoSchema/DeleteSchema.tsx, src/app/ProtoSchema/ProtobufSchemasDisplay.tsx, src/app/assets/languages/en.json, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-12840
=> ISPN-12840 console microcopy edits

package-lock.json, package.json, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-12968
=> ISPN-12968 Fix entry edition content type

payloads/indexStatsOldPayload.json, payloads/queryStatsOldPayload.json, payloads/searchStatsPayload.json, src/app/Caches/CacheMetrics.tsx, src/app/Caches/Query/ClearQueryMetrics.tsx, src/app/Caches/Query/QueryEntries.tsx, src/app/Caches/Query/QueryMetrics.tsx, src/app/IndexManagement/IndexManagement.tsx, src/app/IndexManagement/PurgeIndex.tsx, src/app/IndexManagement/Reindex.tsx, src/app/assets/languages/en.json, src/app/services/statsHook.ts, src/services/ConsoleServices.ts, src/services/cacheService.ts, src/services/searchService.ts, src/types/InfinispanTypes.ts
* Move the Search code to a Search dedicated file
* Remove deprecated query and index stats calls
* Display the new index and query stats
https://issues.redhat.com/browse/ISPN-12458
=> ISPN-12458 Index and Query stats REST API

src/app/assets/languages/en.json
#142 Needs backport to 12.1.x.
=> issue #142 welcome page rewording

src/app/assets/languages/en.json
=> [12.1.x] issue #142 welcome page rewording

package-lock.json, src/app/CacheManagers/CacheTableDisplay.tsx, src/services/dataContainerService.ts, src/services/securityService.ts
https://issues.redhat.com/browse/ISPN-13100
=> ISPN-13100 Create role can remove caches

package-lock.json, src/app/CacheManagers/CacheTableDisplay.tsx, src/services/dataContainerService.ts, src/services/securityService.ts
https://issues.redhat.com/browse/JDG-4667
=> JDG-4667 Create role can remove caches

src/__tests__/services/cacheConfigUtils.test.ts, src/app/AppLayout/AppLayout.tsx, src/app/Caches/Entries/CacheEntries.tsx, src/app/Caches/Entries/CreateOrUpdateEntryForm.tsx, src/app/app.css, src/app/providers/CacheDetailProvider.tsx, src/app/services/cachesHook.ts, src/services/cacheConfigUtils.ts, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-13117
=> ISPN-13117 pagination component fix getKey

scripts/operator/README.md, scripts/operator/cache_xsite_a.yaml, scripts/operator/cache_xsite_b.yaml, scripts/operator/identities_xsitea.yaml, scripts/operator/identities_xsiteb.yaml, scripts/operator/setup.sh, scripts/operator/xsite_a.yaml, scripts/operator/xsite_b.yaml
@dmvolod thanks for your help!
=> Operator with Minikube

src/app/Caches/CacheMetrics.tsx, src/app/Caches/Query/QueryMetrics.tsx, src/services/searchService.ts
https://issues.redhat.com/browse/ISPN-13346
https://issues.redhat.com/browse/ISPN-12308
=> Minor fixes on Query

package.json
https://issues.redhat.com/browse/ISPN-13660
=> ISPN-13660 Update dependencies

cypress/integration/cache-metrics-spec.js, scripts/infinispan-no-secured.xml, src/app/Caches/CacheMetrics.tsx, src/app/assets/languages/en.json
https://issues.redhat.com/browse/ISPN-13510
=> ISPN-13510 Cache Metrics size fix

cypress.json, pom.xml, run-server-for-e2e.sh
I have added new profile to pom.xml which is the same as e2e profile except from the part where it compies just compiled console sources to server. The newly created profile is used in case we want to test the existing server with it's own console sources.
=> Changes for running tests with provided version of server.

cypress/integration/data-container-spec.js, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/Create/EditConfig.tsx, src/app/Caches/Create/GettingStarted.tsx, src/app/Caches/CreateCache.tsx, src/app/assets/languages/en.json
* Basic Wizard Structure created
=> ISPN-13684 - Add the wizard use editor option to create caches with a configuration

src/app/XSite/XSiteCache.tsx, src/services/authService.ts, src/services/cacheService.ts, src/services/fetchCaller.ts, src/services/protobufService.ts
* Correct status display
* Status switch working
=> ISPN-13838 The Cross site status per cache is broken

src/app/XSite/XSiteCache.tsx
https://issues.redhat.com/browse/ISPN-13838
=> Status per cache corrected

src/app/Caches/Create/ConfigurationFeature.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/Create/Features/SecuredCache.tsx, src/app/assets/languages/en.json, src/services/cacheConfigUtils.ts, src/services/infinispanRefData.ts, src/services/securityService.ts, src/types/InfinispanTypes.ts
Feature secured cache added
https://issues.redhat.com/browse/ISPN-13690
=> ISPN-13690 Feature form for secured caches

src/app/Caches/Create/AdvancedOptions.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/services/cacheConfigUtils.ts, src/types/InfinispanTypes.ts
* Switch button on calibrate-by-delete and low-level-trace solved
=> Indexed feature bug-fix on switch button

src/app/CacheManagers/CacheTableDisplay.tsx
https://issues.redhat.com/browse/ISPN-13964
The filter is working fine now, changed some wordings related to cache features,
@karesti Should we extract the `cacheFeature` array to `@services/infinispanRefData`
=> ISPN-13964-Filtering by Transactions and Authorization is not working

src/app/CacheManagers/CacheTableDisplay.tsx
https://issues.redhat.com/browse/ISPN-13805
=> ISPN-13805 Data Container: Hidden filter doesn't work

package-lock.json, package.json
https://issues.redhat.com/browse/ISPN-14011
=> ISPN-14011 Upgrade PTF 2022.08 release

src/app/ProtoSchema/ProtobufSchemasDisplay.tsx, src/app/assets/languages/en.json, src/app/services/protobufHooks.ts
https://issues.redhat.com/browse/ISPN-13894
Warning Alert is used, https://www.patternfly.org/v4/components/alert
=> ISPN-13894 Alert when protobuf schemas are updated

run-server-for-e2e.sh, src/app/Caches/CacheMetrics.tsx, src/services/cacheService.ts
https://issues.redhat.com/browse/ISPN-14061
=> ISPN-14061 Adjust console code to new JSON changes from 14.0.0.CR1

src/app/Caches/Create/Features/IndexedCacheConfigurator.tsx
https://issues.redhat.com/browse/ISPN-14059
=> ISPN-14059 Validation for Indexed feature

src/services/cacheConfigUtils.ts
https://issues.redhat.com/browse/ISPN-14094
=> ISPN-14094 Creating cache with XML/YAML configuration not working

src/app/Caches/Create/AdvancedTuning/TransactionalConfigurationTuning.tsx
https://issues.redhat.com/browse/ISPN-14101
=> ISPN-14101 Wizard: Transaction tooltip fix

src/app/Caches/Create/Features/IndexedCacheConfigurator.tsx, src/services/infinispanRefData.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-14110
=> ISPN-14110 Bugfix: Wizard indexed volatile storage 

src/app/Caches/CacheMetrics.tsx, src/app/Caches/DataDistribution.tsx, src/app/assets/languages/en.json, src/app/services/dataDistributionHook.ts, src/services/cacheService.ts, src/services/infinispanRefData.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-11659
Chart can be viewed using options:
- Total number of entries
- Total memory used
Remaining: applying threshold value
=> ISPN-11659 Data distribution for less than 5 nodes

src/app/Rebalancing/RebalancingConfirmationModal.tsx
https://issues.redhat.com/browse/ISPN-14155
=> ISPN-14155 Cross on rebalance popup window doesn't work

src/app/Caches/Create/Features/PersistentCacheConfigurator.tsx, src/app/assets/languages/en.json
https://issues.redhat.com/browse/ISPN-14097
=> ISPN-14097 Cache wizard persistence caches warning

src/app/Caches/Create/Features/IndexedCacheConfigurator.tsx
https://issues.redhat.com/browse/ISPN-14184
=> ISPN-14184 Wizard: Indexing startup mode not working

cypress/e2e/proto-schema.cy.js, package-lock.json, src/app/ProtoSchema/ProtobufSchemasDisplay.tsx
This PR will resolve https://issues.redhat.com/browse/ISPN-14057
Please review my changes. :)
=> ISPN-14057 Toolbar in Protobuf schema

src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/CreateCache.tsx, src/app/routes.tsx
https://issues.redhat.com/browse/ISPN-14092
=> ISPN-14092 Cache Configuration Wizard Direct Link

cypress/e2e/cluster-welcome.cy.js, cypress/e2e/data-container.cy.js, cypress/e2e/global-stats.cy.js, run-server-for-e2e.sh
I have updated tests to work properly with both upstream and downstream.
=> Updated tests.

cypress/e2e/cache-metrics.cy.js, src/app/Caches/CacheMetrics.tsx, src/app/Caches/DataAccessChart.tsx, src/app/Caches/DataDistribution.tsx, src/app/Caches/DataDistributionChart.tsx, src/app/Caches/DetailCache.tsx, src/app/Common/PopoverHelp.tsx, src/app/assets/languages/en.json, src/services/cacheConfigUtils.ts, src/services/cacheService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-11660
closes #24
=> ISPN-11660 Cache Detail: data distribution +5 nodes

src/app/About/About.tsx, src/app/Welcome/Welcome.tsx
https://issues.redhat.com/browse/ISPN-12586
=> ISPN-12586 Fix the outdated links in the console to the website

src/app/Caches/Create/AdvancedTuning/TransactionalConfigurationTuning.tsx, src/app/assets/languages/en.json, src/services/cacheConfigUtils.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-14237
=> ISPN-14237 Transactional caches should not propose any recovery cache

src/__tests__/services/numberWithComma.test.ts, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/utils/numberWithComma.ts, src/services/countersService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-10038
=> ISPN-10038 Console counters unable to correctly display all long values

src/app/AppLayout/AppLayout.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/Create/CreateCacheGettingStarted.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/CreateCache.tsx, src/app/assets/languages/en.json, src/app/routes.tsx
Reopened to deal correctly observer/admin and the menu confusion
=> ISPN-14092 Direct Link improvements

src/app/Caches/Create/CreateCacheWizard.tsx
https://issues.redhat.com/browse/ISPN-14271
@karesti back button in wizard was not working after PR #275
=> ISPN-14271 Cache wizard back button not working

src/app/Caches/DataDistributionChart.tsx, src/app/assets/languages/en.json, src/services/infinispanRefData.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-14130
=> ISPN-14130 Add the memory option in the data Distribution chart

src/app/AppLayout/AppLayout.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/CreateCache.tsx, src/app/Caches/Query/QueryMetrics.tsx, src/app/assets/languages/en.json, src/app/routes.tsx
https://issues.redhat.com/browse/ISPN-14246
=> ISPN-14246 Query metrics tooltip refactoring

src/app/providers/CreateCacheProvider.tsx
https://issues.redhat.com/browse/ISPN-14322
=> ISPN-14322 Default number of owners is 2

src/app/providers/CreateCacheProvider.tsx
https://issues.redhat.com/browse/ISPN-14322
=> [14.x] ISPN-14322 Default number of owners is 2

src/app/Caches/Query/QueryMetrics.tsx, src/app/assets/languages/en.json
https://issues.redhat.com/browse/ISPN-14246
=> [14.x] ISPN-14246 Query metrics tooltip refactoring

package-lock.json, src/__tests__/views/counters/AddDeltaCounter.test.tsx, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/Counters/AddDeltaCounter.tsx, src/app/assets/languages/en.json, src/app/services/countersHook.ts, src/services/countersService.ts
https://issues.redhat.com/browse/ISPN-14300
=> ISPN-14300 Add a delta in a value

src/app/Caches/DataDistributionChart.tsx, src/app/GlobalStats/ClusterDistributionChart.tsx
https://issues.redhat.com/browse/ISPN-14416
=> ISPN-14416 Data Distribution chart size issue

src/app/Caches/DataDistributionChart.tsx, src/app/GlobalStats/ClusterDistributionChart.tsx
https://issues.redhat.com/browse/ISPN-14416
https://issues.redhat.com/browse/JDG-5832
=> [14.x] Backport ISPN-14416 Data Distribution chart size issue

src/app/Caches/DetailCache.tsx
https://issues.redhat.com/browse/ISPN-14417
=> ISPN-14417 The metrics for misses and retrievals are updated after page reload

src/app/Caches/DetailCache.tsx
https://issues.redhat.com/browse/ISPN-14417
https://issues.redhat.com/browse/JDG-5842
=> [14.x] Backport ISPN-14417 The metrics for misses and retrievals are updated after page reload

src/__tests__/views/counters/DeleteCounter.test.tsx, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/Counters/DeleteCounter.tsx
https://issues.redhat.com/browse/ISPN-14447
=> [14.0] ISPN-14447 Handle RBAC on counters

.github/workflows/pull_requests.yml, cypress.config.ts, cypress/e2e/cache-create-wizard-template.cy.js, cypress/e2e/cache-create-wizard.cy.js, cypress/e2e/cache-detail.cy.js, cypress/e2e/cluster-welcome.cy.js, cypress/e2e/data-container.cy.js, cypress/e2e/proto-schema.cy.js, cypress/e2e/rbac_func.cy.js, data/caches/childData.json, data/caches/indexedCacheNonAuth.json, data/caches/textCache.json, data/create-data.sh, data/schemas/car.proto, data/schemas/child.proto, run-server-for-e2e.sh, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/Caches/CacheMetrics.tsx, src/app/Caches/DataAccessChart.tsx, src/app/Caches/DataDistributionChart.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/Query/ClearQueryMetrics.tsx, src/app/Caches/Query/QueryMetrics.tsx
New tests are added testing RBAC, Metrics page.
=> New tests implemented.

src/app/Caches/DetailCache.tsx, src/app/assets/languages/en.json
https://issues.redhat.com/browse/ISPN-12106
=> [14.0] ISPN-12106 Add a refresh button in the cache detail

src/app/providers/CreateCacheProvider.tsx
https://issues.redhat.com/browse/ISPN-14394
=> ISPN-14394 Cache Configuration Wizard indexing startup mode

src/app/providers/CreateCacheProvider.tsx
https://issues.redhat.com/browse/ISPN-14394
=> [14.0] ISPN-14394 Cache Configuration Wizard indexing startup mode

.github/workflows/pull_requests.yml
=> [14.x] Fixed the workflow in case of push event.

.github/workflows/pull_requests.yml
=> Fixed the workflow in case of push event.

package-lock.json, package.json
https://issues.redhat.com/browse/ISPN-14694
=> ISPN-14694 Upgrade Patternfly Dependencies to Release 2023.02 (2023-03-24)

package-lock.json, package.json
https://issues.redhat.com/browse/ISPN-14694
=> [14.0] ISPN-14694 Upgrade Patternfly Dependencies to Release 2023.02 (2023-03-24)

src/app/Caches/DetailCache.tsx
(Reopened)
https://issues.redhat.com/browse/ISPN-12106
=> ISPN-12106 Add a refresh button in the cache detail

src/app/assets/languages/en.json
https://issues.redhat.com/browse/ISPN-14741
The bug has already been solved for the main branch. #319
=> [14.0] ISPN-14741 Console link direct to a wrong page

src/app/Caches/Configuration/CacheConfiguration.tsx, src/app/Caches/DetailCache.tsx, src/app/assets/languages/en.json
https://issues.redhat.com/browse/ISPN-14761
=> ISPN-14761 Displays encoding message for Java and JBoss marshalling

src/app/Caches/DetailCache.tsx, src/app/providers/CacheDetailProvider.tsx, src/app/utils/encodingUtils.ts
https://issues.redhat.com/browse/ISPN-14682
=> ISPN-14682 Do not retrieve entries when no encoding in cache

src/services/protobufService.ts
https://issues.redhat.com/browse/ISPN-13909
=> ISPN-13909 Special symbols handling during Protobuf schema creation

src/services/protobufService.ts
https://issues.redhat.com/browse/ISPN-13909
=> [14.0] ISPN-13909 Special symbols handling during Protobuf schema creation

src/app/Caches/DetailCache.tsx, src/app/providers/CacheDetailProvider.tsx, src/app/utils/encodingUtils.ts
https://issues.redhat.com/browse/ISPN-14682
=> [14.0] ISPN-14682 Do not retrieve entries when no encoding in cache

src/app/utils/encodingUtils.ts
Resolving TypeError from encodingUtils file
=> Encoding utils error

src/app/utils/encodingUtils.ts
=> [14.0] Encoding utils error

cypress/e2e/proto-schema.cy.js, run-server-for-e2e.sh
Also updated the script to latest infinispan version, and updated the part for being able to use the predefined server build.
=> [14.x] Fixed proto-schema.cy.js after special symbols issue is fixed.

src/services/infinispanRefData.ts
Changing `application/x-java-serialized` to `application/x-java-serialized-object`
=> Java Serialized encoding bug

src/services/infinispanRefData.ts
Changing `application/x-java-serialized` to `application/x-java-serialized-object`
=> [14.0] Java Serialized encoding bug

src/services/cacheConfigUtils.ts
https://issues.redhat.com/browse/ISPN-14856
Back-porting #354
=> [14.0] ISPN-14856 Do not show Isolation locking property when not transactional cache

package-lock.json, package.json
https://issues.redhat.com/browse/JDG-6220
=> JDG-6220 CVE-2023-0842 xml2js: node-xml2js: xml2js is vulnerable to prototype pollution [jdg-8]

package-lock.json, package.json
https://issues.redhat.com/browse/JDG-6220
=> [14.x]  JDG-6220 CVE-2023-0842 xml2js: node-xml2js: xml2js is vulnerable to prototype pollution [jdg-8]

src/__tests__/services/cacheConfigUtils.test.ts, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/assets/languages/en.json, src/services/cacheConfigUtils.ts, src/services/dataContainerService.ts, src/services/displayUtils.ts, src/services/infinispanRefData.ts
https://issues.redhat.com/browse/ISPN-14878
=> ISPN-14878 Clear functionality from scattered caches

cypress/e2e/cluster-welcome.cy.js, cypress/e2e/data-container.cy.js, cypress/e2e/rbac_func.cy.js
I have fixed the console tests which were failing after ISPN-14718 was implemented.
=> Fixing tests after ISPN-14718 is implemented.

cypress/e2e/cluster-welcome.cy.js, src/app/About/About.tsx, src/app/AppLayout/AppLayout.tsx, src/app/services/serverHook.ts
https://issues.redhat.com/browse/ISPN-14912
=> ISPN-14912 About page

src/app/Caches/DetailCache.tsx, src/app/IndexManagement/IndexManagement.tsx, src/services/displayUtils.ts
https://issues.redhat.com/browse/ISPN-14915
=> ISPN-14915 Cache detail header

cypress/e2e/cache-create-wizard.cy.js, cypress/e2e/data-container.cy.js, cypress/e2e/rbac_func.cy.js, src/__tests__/services/displayUtils.test.ts, src/__tests__/views/caches/DeleteCache.test.tsx, src/__tests__/views/caches/IgnoreCache.test.tsx, src/__tests__/views/caches/SetAvailableCache.test.tsx, src/app/CacheManagers/CacheManagers.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/CacheManagers/TasksTableDisplay.tsx, src/app/Caches/DeleteCache.tsx, src/app/Caches/IgnoreCache.tsx, src/app/Caches/SetAvailableCache.tsx, src/app/Common/CacheTypeBadge.tsx, src/app/ProtoSchema/ProtobufSchemasDisplay.tsx, src/app/assets/languages/en.json, src/app/services/cachesHook.ts, src/app/utils/searchFilter.ts, src/services/displayUtils.ts, src/services/infinispanRefData.ts
https://issues.redhat.com/browse/ISPN-14961
=> ISPN-14961 Cache table

src/app/Caches/Configuration/CacheConfiguration.tsx
https://issues.redhat.com/browse/ISPN-14917
=> ISPN-14917 Configuration tab

cypress/e2e/data-container.cy.js, pom.xml, src/__tests__/services/downloadServerReport.test.ts, src/__tests__/services/formatAge.test.ts, src/app/Caches/Configuration/CacheConfiguration.tsx, src/app/Caches/Configuration/DetailConfigurations.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/ConnectedClients/ConnectedClients.tsx, src/app/Welcome/Welcome.tsx, src/app/assets/languages/en.json, src/app/routes.tsx, src/app/services/cachesHook.ts, src/app/services/clusterHook.ts, src/app/services/serverHook.ts, src/app/utils/formatAge.ts, src/services/serverService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-14966
=> ISPN-14966 Connected clients page

src/app/AppLayout/AppLayout.tsx, src/app/assets/languages/en.json
https://issues.redhat.com/browse/ISPN-15019
=> ISPN-15019 Fix header logo

src/__tests__/services/downloadServerReport.test.ts, src/app/ClusterStatus/ClusterStatus.tsx, src/app/services/clusterHook.ts
https://issues.redhat.com/browse/ISPN-15044
=> ISPN-15044 Cluster membership page

cypress/e2e/cache-detail.cy.js, cypress/e2e/rbac_func.cy.js, src/app/Caches/Query/QueryEntries.tsx, src/app/assets/languages/en.json
https://issues.redhat.com/browse/ISPN-15077
=> ISPN-15077 Ickle query page

src/app/GlobalStats/ClusterDistributionChart.tsx
https://issues.redhat.com/browse/ISPN-15158
=> ISPN-15158 Memory used and memory available labels are swapped

src/app/GlobalStats/ClusterDistributionChart.tsx
https://issues.redhat.com/browse/ISPN-15158
=> [14.x] ISPN-15158 Memory used and memory available labels are swapped

README.md
Adding a description of Weblate Translations and how to contribute.
=> Readme for Weblate translations

pom.xml
Self checklist (all need to be checked):
=> update node version to v18.18.0

CONTRIBUTING.md
CONTIBUTION.md file for hacktoberfest  and Community Contributions.
=> Contributions.md

cypress/e2e/1_acess_management.cy.js, cypress/e2e/1_rbac_func.cy.js, src/app/AccessManagement/AccessManager.tsx, src/app/AccessManagement/RoleTableDisplay.tsx, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/Caches/Create/Features/SecuredCacheConfigurator.tsx, src/app/app.css, src/app/assets/languages/en.json, src/app/index.tsx, src/app/routes.tsx, src/app/services/rolesHook.ts, src/app/utils/searchFilter.ts, src/services/infinispanRefData.ts, src/services/securityService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-14695
=> ISPN-14695 Role list display

src/app/Caches/Entries/CacheEntries.tsx, src/app/Caches/Entries/CreateOrUpdateEntryForm.tsx
https://issues.redhat.com/browse/ISPN-15257
=> ISPN-15257 Fixes initial values from string to String when needed

cypress/e2e/1_acess_management.cy.js, src/app/AccessManagement/AccessManager.tsx, src/app/AccessManagement/FlushRoleCacheModal.tsx, src/app/CacheManagers/CacheManagers.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/Entries/CacheEntries.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/ConnectedClients/ConnectedClients.tsx, src/app/GlobalStats/GlobalStats.tsx, src/app/IndexManagement/IndexManagement.tsx, src/app/Rebalancing/RebalancingCache.tsx, src/app/Rebalancing/RebalancingCacheManager.tsx, src/app/XSite/XSiteCache.tsx, src/app/assets/languages/en.json, src/app/services/rolesHook.ts, src/services/securityService.ts
https://issues.redhat.com/browse/ISPN-14716
=> ISPN-14716 flush cache

src/app/Caches/Configuration/DetailConfigurations.tsx, src/app/Caches/DataDistributionChart.tsx, src/app/Caches/Entries/CacheEntries.tsx, src/app/Caches/Query/QueryEntries.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/ConnectedClients/ConnectedClients.tsx, src/app/XSite/XSiteCache.tsx, src/app/assets/languages/en.json, src/app/routes.tsx, src/services/crossSiteReplicationService.ts
https://issues.redhat.com/browse/ISPN-15285
=> ISPN-15285 clean deprecated table

cypress/e2e/1_acess_management.cy.js, src/app/AccessManagement/CreateRole.tsx, src/app/AccessManagement/DeleteRole.tsx, src/app/AccessManagement/RoleDetail.tsx, src/app/AccessManagement/RoleDetailContent/AddPermissions.tsx, src/app/AccessManagement/RoleDetailContent/RemovePermission.tsx, src/app/AccessManagement/RoleDetailContent/RoleCaches.tsx, src/app/AccessManagement/RoleDetailContent/RoleGeneral.tsx, src/app/AccessManagement/RoleDetailContent/RolePermissions.tsx, src/app/AccessManagement/RoleTableDisplay.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/DetailCache.tsx, src/app/Common/DataContainerBreadcrumb.tsx, src/app/Common/SelectMultiWithChips.tsx, src/app/Common/TableErrorState.tsx, src/app/Common/TableLoadingState.tsx, src/app/assets/languages/en.json, src/app/routes.tsx, src/app/services/rolesHook.ts, src/services/displayUtils.ts, src/services/infinispanRefData.ts, src/services/securityService.ts
https://issues.redhat.com/browse/ISPN-14697
=> ISPN-14697 Role Detail

src/app/Caches/Create/CacheConfigEditor.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/Create/DownloadCacheModal.tsx, src/app/Caches/Create/LanguageToggleRadios.tsx, src/app/Caches/Create/ReviewCacheConfig.tsx, src/app/ProtoSchema/CreateProtoSchema.tsx, src/app/ProtoSchema/ProtobufSchemasDisplay.css, src/services/cacheConfigUtils.ts, src/services/cacheService.ts
Closes: #401 
This is a feature request ISPN-14098, to add a feature to review the configurations in JSON, XML and YAML at Cache Configuration review step.
As a part of this, added content Type parameter in following api :
createCacheWithWizardStep,
convertConfigFormat,
so that we can convert the formats from and to any format (previously we were converting to JSON hardcoded),
Added toggle radio buttons to change between different configurations.
changes in UI:
Tested on local environment.
Manual testing is done on browsers,
Self checklist (all need to be checked):
=> ISPN-14098  Review configuration in JSON, XML and YAML #401

src/app/AccessManagement/AccessManager.tsx, src/app/AccessManagement/PrincipalTableDisplay.tsx, src/app/Welcome/Welcome.tsx, src/app/assets/languages/en.json, src/app/services/principalsHook.ts, src/services/securityService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-14699
=> ISPN-14699 principals list

cypress/e2e/1_acess_management.cy.js, src/__tests__/views/NotFound.test.tsx, src/app/AccessManagement/AccessManager.tsx, src/app/AccessManagement/CreateRole.tsx, src/app/AccessManagement/GrantNewAccess.tsx, src/app/AccessManagement/ManageRolesForPrincipal.tsx, src/app/AccessManagement/PrincipalTableDisplay.tsx, src/app/AccessManagement/RemovePrincipal.tsx, src/app/AccessManagement/RoleDetail.tsx, src/app/AccessManagement/RoleDetailContent/AddPermissions.tsx, src/app/AccessManagement/RoleDetailContent/RoleCaches.tsx, src/app/AccessManagement/RoleDetailContent/RolePermissions.tsx, src/app/AccessManagement/RoleTableDisplay.tsx, src/app/assets/languages/en.json, src/app/services/principalsHook.ts, src/services/cacheService.ts, src/services/infinispanRefData.ts, src/services/securityService.ts, src/test-utils.tsx
https://issues.redhat.com/browse/ISPN-14702
=> ISPN-14702 Grant and deny new access

cypress/e2e/1_acess_management.cy.js, src/app/AccessManagement/AccessManager.tsx, src/app/AccessManagement/GrantNewAccess.tsx, src/app/AccessManagement/PrincipalTableDisplay.tsx, src/app/AccessManagement/UsersTableDisplay.tsx, src/app/Welcome/Welcome.tsx, src/app/assets/languages/en.json, src/app/services/userManagementHook.ts, src/services/securityService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-15321
=> ISPN-15321 Display users from realms

README.md, keycloak/docker-compose.yaml, keycloak/infinispan-keycloak-realm.json, keycloak/infinispan-token-realm.yaml, package-lock.json, package.json, src/app/AppLayout/AppLayout.tsx, src/app/GlobalStats/GlobalStats.tsx, src/app/index.tsx, src/app/providers/UserContextProvider.tsx, src/app/routes.tsx, src/app/services/userManagementHook.ts, src/services/fetchCaller.ts, src/services/keycloakService.ts
https://issues.redhat.com/browse/ISPN-15359
=> ISPN-15359 Fixes Keycloak integration

README.md, keycloak/docker-compose.yaml, keycloak/infinispan-keycloak-realm.json, keycloak/infinispan-token-realm.yaml, src/app/AppLayout/AppLayout.tsx, src/app/index.tsx, src/app/providers/UserContextProvider.tsx, src/app/routes.tsx, src/app/services/userManagementHook.ts
https://issues.redhat.com/browse/ISPN-15359
=> ISPN-15359 Fixes Keycloak integration in the console

keycloak/docker-compose.yaml, src/app/Welcome/Welcome.tsx, src/app/routes.tsx
https://issues.redhat.com/browse/ISPN-15359
=> ISPN-15359 Welcome page fix

src/app/Caches/Create/ReviewCacheConfig.tsx, src/services/cacheConfigUtils.ts
https://issues.redhat.com/browse/ISPN-15370
=> Fixes small bug on persistence config parse

src/app/CacheManagers/CacheManagers.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/Create/ReviewCacheConfig.tsx, src/app/Common/Health.tsx, src/app/Common/Status.tsx, src/app/Rebalancing/RebalancingCacheManager.tsx, src/app/Welcome/Welcome.tsx
https://issues.redhat.com/browse/ISPN-15624
=> Site name container page

src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/Create/Features/BackupsCacheConfigurator.tsx
https://issues.redhat.com/browse/ISPN-15283
=> ISPN-15283 Upgrade deprecated wizard

cypress/e2e/1_cluster-welcome.cy.js, cypress/e2e/1_data-container.cy.js, cypress/e2e/1_global-stats.cy.js, cypress/e2e/1_rbac_func.cy.js, src/__tests__/views/caches/IgnoreCache.test.tsx, src/app/About/About.tsx, src/app/CacheManagers/CacheManagers.tsx, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/Configuration/DetailConfigurations.tsx, src/app/Caches/Create/CacheConfigEditor.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/CreateCache.tsx, src/app/Caches/IgnoreCache.tsx, src/app/GlobalStats/GlobalStats.tsx, src/app/Rebalancing/RebalancingCacheManager.tsx, src/app/Welcome/Welcome.tsx, src/app/assets/languages/en.json, src/app/providers/CacheManagerContextProvider.tsx, src/app/routes.tsx, src/app/services/cachesHook.ts, src/app/services/serverHook.ts, src/app/services/statsHook.ts, src/services/authService.ts, src/services/cacheService.ts, src/services/dataContainerService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-15762
=> ISPN-15762 cleanup cache manager use

src/app/About/About.tsx, src/app/Welcome/Welcome.tsx
https://issues.redhat.com/browse/ISPN-16051
=> ISPN-16051 About background image is broken in bundle

src/app/ClearMetrics/ClearMetrics.tsx
https://issues.redhat.com/browse/ISPN-16052
=> ISPN-16052 Refresh on clear metrics

.eslintrc, jest.config.js, package-lock.json, package.json, src/__tests__/components/BannerAlert.test.tsx, src/__tests__/components/Health.test.tsx, src/__tests__/views/About.test.tsx, src/__tests__/views/CacheConfiguration.test.tsx, src/__tests__/views/NotFound.test.tsx, src/__tests__/views/Support.test.tsx, src/__tests__/views/schemas/EditSchema.test.tsx, src/index.tsx, webpack.common.js, webpack.dev.js, webpack.prod.js
https://issues.redhat.com/browse/ISPN-16132
=> ISPN-16132 Fixes Monaco Editor

cypress/e2e/1_cluster-welcome.cy.js, cypress/e2e/3_proto-schema.cy.js
Fixes the Welcome page cypress tests as they are failing for productized version of Console.
=> Fixed Welcome page tests to fit productized version.

cypress/e2e/1_cluster-welcome.cy.js, scripts/infinispan-basic-auth.xml, src/app/CacheManagers/CacheManagers.tsx, src/app/Common/TracingEnabled.tsx, src/app/ConnectedClients/ConnectedClients.tsx, src/app/Rebalancing/RebalancingCacheManager.tsx, src/app/assets/languages/en.json, src/app/utils/getLanguage.ts, src/services/dataContainerService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-16190
=> ISPN-16190 Display if tracing is enabled in the data container page

cypress/e2e/3_cache-crud-wizard.cy.js, src/app/Caches/Create/AdvancedOptionsConfigurator.tsx, src/app/Caches/Create/AdvancedTuning/IndexedConfigurationTuning.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/Create/Features/TracingCacheConfigurator.tsx, src/app/Caches/Create/FeaturesSelector.tsx, src/app/Caches/Create/ReviewCacheConfig.tsx, src/app/Caches/CreateCache.tsx, src/app/assets/languages/en.json, src/app/providers/CreateCacheProvider.tsx, src/services/cacheConfigUtils.ts, src/services/cacheService.ts, src/services/dataContainerService.ts, src/services/displayUtils.ts, src/types/InfinispanTypes.ts, webpack.prod.js
https://issues.redhat.com/browse/ISPN-16163
=> ISPN-16163 Tracing feature

src/app/assets/languages/en.json, src/app/assets/languages/it.json
https://issues.redhat.com/browse/fix_intro_text
=> Fix intro text description according to new website wording

cypress/e2e/2_cache-tracing.cy.js, src/app/CacheManagers/CacheManagers.tsx, src/app/Caches/Create/Features/BackupsCacheConfigurator.tsx, src/app/Caches/Create/Features/TracingCacheConfigurator.tsx, src/app/Caches/Create/FeaturesSelector.tsx, src/app/Caches/CreateCache.tsx, src/app/Caches/DetailCache.tsx, src/app/Common/TracingEnabled.tsx, src/app/Rebalancing/RebalancingCache.tsx, src/app/TracingManagement/TracingManagement.tsx, src/app/assets/languages/en.json, src/app/routes.tsx, src/app/services/configHook.ts, src/services/cacheService.ts, src/services/dataContainerService.ts, src/services/infinispanRefData.ts
https://issues.redhat.com/browse/ISPN-16187
=> ISPN-16187 Manage tracing per cache

cypress/e2e/1_rbac_func.cy.js, src/app/Caches/Entries/CacheEntries.tsx
https://issues.redhat.com/browse/ISPN-14450
=> ISPN-14450 Remove actions for users without WRITE permission

src/app/Common/TracingEnabled.tsx
=> ISPN-16187 Put grey color when disabled

cypress/e2e/3_proto-schema.cy.js, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/Create/FeaturesSelector.tsx, src/app/Caches/Create/LanguageToggleRadios.tsx, src/app/Caches/Create/ReviewCacheConfig.tsx
https://issues.redhat.com/browse/ISPN-16256
=> ISPN-16256 Don't validate config on every step

src/app/Caches/Create/CreateCacheGettingStarted.tsx
https://issues.redhat.com/browse/ISPN-16206
=> ISPN-16206 Allow spaces on cache name

src/app/Caches/Entries/CacheEntries.tsx, src/app/assets/languages/en.json, src/app/providers/CacheDetailProvider.tsx, src/app/services/cachesHook.ts
https://issues.redhat.com/browse/ISPN-16264
=> ISPN-16264 Add limit select to display up to 1000 entries

src/app/CacheManagers/CacheManagers.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/Create/LanguageToggleRadios.tsx, src/app/Caches/Create/ReviewCacheConfig.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/Entries/CacheEntries.tsx, src/app/Caches/Query/QueryEntries.tsx, src/app/Common/TracingEnabled.tsx, src/app/TracingManagement/TracingManagement.tsx, src/app/assets/languages/en.json, src/app/providers/CacheDetailProvider.tsx, src/app/services/cachesHook.ts, src/app/services/searchHook.ts, src/services/fetchCaller.ts, src/services/searchService.ts, src/types/InfinispanTypes.ts
* Use POST API to send the search query with the body
* Parse corretly Search API Bad Request errors
* Fix pagination
* Retrieve and use total results correctly
https://issues.redhat.com/browse/ISPN-16199
=> ISPN-16199 Search fixes

src/app/Caches/Create/AdvancedOptionsConfigurator.tsx, src/app/Common/SelectMultiWithChips.tsx, src/app/assets/languages/en.json, src/app/providers/CreateCacheProvider.tsx, src/services/cacheConfigUtils.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-16258
=> ISPN-16258 Include cache alias in the creation wizard

cypress/e2e/1_cluster-welcome.cy.js, cypress/e2e/3_proto-schema.cy.js
The PR contains 2 test fixes, i.e. one of them fails during DG testing, the other one fails randomly.
=> Updated tests as they are failing in different circumstances.

src/app/Caches/CacheMetrics.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/Query/QueryEntries.tsx, src/services/searchService.ts
https://issues.redhat.com/browse/ISPN-16496
=> ISPN-16496 Display query stats for all queryable caches

src/__tests__/services/cacheConfigUtils.test.ts, src/app/Caches/DetailCache.tsx, src/app/Caches/Entries/CacheEntries.tsx, src/services/cacheConfigUtils.ts, src/services/cacheService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-16529
=> ISPN-16529 Display entries with all encodings

cypress/e2e/1_rbac_func.cy.js, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/CacheMetrics.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/Entries/CacheEntries.tsx, src/app/Common/Health.tsx, src/app/assets/languages/en.json, src/app/providers/CacheDetailProvider.tsx, src/app/utils/encodingUtils.ts, src/services/cacheService.ts, src/services/fetchCaller.ts, src/services/infinispanRefData.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-16412
=> ISPN-16412 Display cache config when not Healthy

cypress/e2e/3_cache-aliases.cy.js, cypress/e2e/3_cache-ignore.cy.js, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/SetAvailableCache.tsx, src/app/Caches/UpdateAliasCache.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/assets/languages/en.json, src/app/services/configHook.ts, src/app/utils/searchFilter.ts, src/services/cacheService.ts, src/services/dataContainerService.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-16580
Depends on https://github.com/infinispan/infinispan/pull/12865
=> ISPN-16580 Display aliases in caches

src/app/AppLayout/AppLayout.tsx
https://issues.redhat.com/browse/ISPN-16599
=> ISPN-16599 Fix character in the about menu

cypress/e2e/1_rbac_func.cy.js, src/app/CacheManagers/CacheTableDisplay.tsx, src/app/Caches/CacheMetrics.tsx, src/app/Caches/Create/FeaturesSelector.tsx, src/app/Caches/DetailCache.tsx, src/app/Caches/Entries/CacheEntries.tsx, src/app/Common/Health.tsx, src/app/Common/SelectMultiWithChips.tsx, src/app/ConnectedClients/ConnectedClients.tsx, src/app/assets/languages/en.json, src/app/providers/CacheDetailProvider.tsx, src/app/utils/encodingUtils.ts, src/app/utils/getLanguage.ts, src/services/cacheConfigUtils.ts, src/services/cacheService.ts, src/services/fetchCaller.ts, src/services/infinispanRefData.ts, src/types/InfinispanTypes.ts
https://issues.redhat.com/browse/ISPN-16412
depends on https://github.com/infinispan/infinispan/pull/12872
=> [15.0] ISPN-16412 View failed caches config

src/app/Caches/Create/CreateCacheWizard.tsx, src/app/Caches/Create/Features/BackupsCacheConfigurator.tsx, src/app/Caches/Create/FeaturesSelector.tsx
=> Closes 529 x-site feature console

src/app/AppLayout/AppLayout.tsx
=> Closes 494 ? misaligned

src/services/keycloakService.ts
keycloak without using redirect url
=> Logout keycloak without url

cypress/e2e/1_acess_management.cy.js, cypress/e2e/1_cluster-welcome.cy.js, cypress/e2e/1_global-stats.cy.js, cypress/e2e/1_rbac_func.cy.js, cypress/e2e/2_cache-detail.cy.js, cypress/e2e/2_cluster-membership.cy.js, cypress/e2e/3_cache-crud-wizard.cy.js, cypress/e2e/3_client-connection.cy.js, cypress/e2e/3_proto-schema.cy.js, src/app/AccessManagement/RemovePrincipal.tsx, src/app/ClusterStatus/ClusterStatus.tsx, src/app/GlobalStats/GlobalStats.tsx
Backport for #493 
Doesn't contain tests for tracing and alias functionality.
=> [15.0] Added new Cypress Tests.

jest.config.js, package-lock.json, package.json, tsconfig.json
=> [15.0] Closes #534 Updates to Keycloak 26

.github/workflows/pull_requests.yml, cypress/e2e/1_cluster-welcome.cy.js, cypress/e2e/1_data-container.cy.js, cypress/e2e/4_xsite.cy.js, data/caches/xsiteLON.json, data/caches/xsiteNYC.json, data/create-data.sh, run-server-for-e2e-container.sh, scripts/infinispan-basic-auth.xml, src/app/Caches/Create/AdvancedTuning/BackupsCofigurationTuning.tsx, src/app/Caches/Create/AdvancedTuning/BackupsSiteConfigurator.tsx, src/app/Caches/Create/Features/BackupsCacheConfigurator.tsx, src/app/XSite/StateTransfer.tsx, src/app/XSite/XSiteCache.tsx
=> Added new tests covering x-site replication cases.

.github/workflows/pull_requests.yml, cypress/e2e/1_cluster-welcome.cy.js, cypress/e2e/1_data-container.cy.js, cypress/e2e/3_counters.cy.js, cypress/e2e/4_xsite.cy.js, data/caches/xsiteLON.json, data/caches/xsiteNYC.json, data/create-data.sh, run-server-for-e2e-container.sh, scripts/infinispan-basic-auth.xml, src/app/Caches/Create/AdvancedTuning/BackupsCofigurationTuning.tsx, src/app/Caches/Create/AdvancedTuning/BackupsSiteConfigurator.tsx, src/app/Caches/Create/Features/BackupsCacheConfigurator.tsx, src/app/XSite/StateTransfer.tsx, src/app/XSite/XSiteCache.tsx
Backport PR for #540 
Closes: #531
=> [15.0] Added tests for xsite testing.

src/app/providers/UserContextProvider.tsx, src/services/keycloakService.ts
=> Fixes keycloak integration

src/__tests__/views/NotFound.test.tsx, src/app/NotFound/NotFound.tsx
=> [#548] Use MissingPage component

src/app/AccessManagement/FlushRoleCacheModal.tsx
=> [#566] Fix Flush ACL cache modal

keycloak/infinispan-keycloak-realm.json
May relate to #557 
Fixed the keycloak config for running from keycloak/ directory.
=> Fixed keycloak configuration to work properly with KC 25+

.githooks/commit-msg, .githooks/configure-hooks, .githooks/configure-hooks.bat, .gitmessage, build.xml, pom.xml
https://github.com/infinispan/infinispan-console/issues/573
=> [#573] Git commit message template and validation

.github/workflows/release.yml, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd, pom.xml
https://issues.redhat.com/browse578
=> [#578] Publish to Sonatype Central

cypress/e2e/3_cache-crud-wizard.cy.js, src/app/Caches/CreateCache.tsx, src/app/routes.tsx
=> [#542] Create cache is not for admins only

.github/workflows/pull_requests.yml, cypress/e2e/5_empty_display.cy.js, src/app/CacheManagers/CounterTableDisplay.tsx, src/app/ProtoSchema/CreateProtoSchema.tsx, src/app/ProtoSchema/ProtobufSchemasDisplay.tsx
=> [15.2] [#583] Fix schemas and counters display

cypress/e2e/1_rbac_func.cy.js, cypress/e2e/2_cache-detail.cy.js, cypress/e2e/3_cache-aliases.cy.js, src/app/Caches/DetailCache.tsx, src/app/assets/languages/en.json
=> [#527] Update alias from cache detail

cypress/e2e/1_cluster-welcome.cy.js, cypress/e2e/2_cache-detail.cy.js, src/app/About/About.tsx, src/app/Caches/Entries/CacheEntries.tsx, src/app/assets/languages/en.json, src/services/displayUtils.ts
=> [#587] Add a truncate values checkbox

src/app/Caches/Create/BasicCacheConfigConfigurator.tsx, src/app/Caches/Create/CreateCacheWizard.tsx, src/services/cacheConfigUtils.ts, src/services/dataContainerService.ts, src/types/InfinispanTypes.ts
=> [#591] Local mode, local caches

cypress/e2e/2_cache-expiration.cy.js, cypress/e2e/2_cache-tracing.cy.js, cypress/e2e/3_cache-aliases.cy.js, src/__tests__/services/convertToTimeQuantity.test.ts, src/app/Caches/Configuration/DetailConfigurations.tsx, src/app/Caches/Configuration/EditConfiguration.tsx, src/app/Caches/Create/BasicCacheConfigConfigurator.tsx, src/app/Caches/Create/TimeQuantityInputGroup.tsx, src/app/Caches/DetailCache.tsx, src/app/Common/SelectSingle.tsx, src/app/assets/languages/en.json, src/app/providers/CacheDetailProvider.tsx, src/app/routes.tsx, src/app/services/configHook.ts, src/app/utils/convertToTimeQuantity.ts, src/services/cacheService.ts, src/types/InfinispanTypes.ts
Closes  #593 
For admins only
Update runtime properties. Expiration maxidle and lifespan
=> [#593] Update expiration at runtime

cypress/e2e/1_data-container.cy.js, cypress/e2e/6_cache-bounded-config-edition.cy.js, cypress/e2e/6_cache-expiration-config-edition.cy.js, data/caches/jsonCache.json, package-lock.json, package.json, src/__tests__/services/convertToSizeAndUnit.test.ts, src/app/Caches/Configuration/EditConfiguration.tsx, src/app/Caches/Configuration/Features/BoundedConfigEdition.tsx, src/app/Caches/Configuration/Features/ExpirationConfigEdition.tsx, src/app/Caches/Configuration/Features/TabsToolbar.tsx, src/app/Caches/Create/Features/BoundedCacheConfigurator.tsx, src/app/assets/languages/en.json, src/app/providers/CacheDetailProvider.tsx, src/app/services/configHook.ts, src/app/utils/convertToSizeAndUnit.ts, src/app/utils/validateInputNumber.ts, src/services/cacheService.ts, src/types/InfinispanTypes.ts
=> [#572] Update bounded caches configuration at runtime

cypress/e2e/6_cache-expiration-config-edition.cy.js, cypress/e2e/6_cache-indexed-config-edition.cy.js, cypress/e2e/6_cache-secured-config-edition.cy.js, src/app/Caches/Configuration/EditConfiguration.tsx, src/app/Caches/Configuration/Features/SecurityConfigEdition.tsx, src/app/assets/languages/en.json, src/services/cacheConfigUtils.ts, src/services/cacheService.ts, src/types/InfinispanTypes.ts
=> [#599] Security config update

cypress/e2e/1_rbac_func.cy.js, src/app/routes.tsx
=> [#623] Cluster membership for admins
