infinispan/infinispan-console

src/app/CacheManagers/CacheManagers.tsx
src/app/CacheManagers/CacheTableDisplay.tsx
src/app/CacheManagers/CreateProtoSchema.tsx
src/app/CacheManagers/DeleteCache.tsx
src/app/CacheManagers/DeleteSchema.tsx
src/app/CacheManagers/IgnoreCache.tsx
src/app/CacheManagers/ProtobufSchemasDisplay.tsx
src/app/Caches/CreateOrUpdateEntryForm.tsx
src/services/cacheService.ts
src/services/dataContainerService.ts
src/services/formUtils.ts
src/services/protobufService.ts
src/services/utils.ts
src/types/InfinispanTypes.ts

https://issues.redhat.com/browse/ISPN-11663
https://issues.redhat.com/browse/ISPN-11664
https://issues.redhat.com/browse/ISPN-11665
https://issues.redhat.com/browse/ISPN-11666

Protobuf manipulation

---

src/app/Caches/CacheMetrics.tsx
src/app/GlobalStats/GlobalStats.tsx

https://issues.redhat.com/browse/ISPN-12311
https://issues.redhat.com/browse/JDG-3922

ISPN-12311 Fix data access % in chart

---

package.json
pom.xml

Cypress fails to install in PNC. It tries to download a lot of stuff from the internet which is blocked in PNC. 
The default "npm install" always tries to install it even without enabling "e2e". This is the only way I found to solve the issue.

Remove cypress from package.json

---

src/__tests__/services/cacheConfigUtils.test.ts
src/app/Caches/CreateCache.tsx
src/app/Caches/DetailCache.tsx
src/app/assets/languages/en.json
src/services/cacheConfigUtils.ts

https://issues.redhat.com/browse/ISPN-13218

ISPN-13218 improve error messages on cache creation

---

src/app/CacheManagers/CacheManagers.tsx
src/app/CacheManagers/CacheTableDisplay.tsx
src/app/CacheManagers/RebalancingCacheManager.tsx
src/app/Caches/DetailCache.tsx
src/app/Caches/RebalancingCache.tsx
src/app/assets/languages/en.json
src/app/providers/CacheDetailProvider.tsx
src/app/providers/CacheManagerContextProvider.tsx
src/app/services/cachesHook.ts
src/app/services/dataContainerHooks.ts
src/services/cacheConfigUtils.ts
src/services/cacheService.ts
src/services/dataContainerService.ts
src/types/InfinispanTypes.ts

This PR includes for facility and testing 3 rebalancing features.
Only for admins (observer should not access this feature for example)
* Enable/disable rebalancing at cluster level
* Enable/disable rebalancing at cache level if rebalancing is enabled at cluster level.
For all the users
* Display a "rebalancing off" badge in the cache list when rebalancing is enabled at cluster level and the cache in the list has rebalancing disabled.
Cluster Level
Cache Level
>
If rebalancing is globally disabled, the cache detail does not display anything
Cluster View List of Caches. When the cache has rebalancing disabled, display a badge.
Depends on this PR: https://github.com/infinispan/infinispan/pull/9519

ISPN-11492 Cluster and Cache enable/disable rebalancing

---

src/app/CacheManagers/CacheTableDisplay.tsx
src/app/Caches/SetAvailableCache.tsx
src/app/assets/languages/en.json
src/services/cacheService.ts

https://issues.redhat.com/browse/ISPN-13373
* Feature to make cache available from Degraded mode

ISPN-13373 Allow Cache availability to be configured via the console

---

src/app/Caches/DataDistributionChart.tsx
src/app/assets/languages/en.json
src/services/infinispanRefData.ts
src/types/InfinispanTypes.ts

https://issues.redhat.com/browse/ISPN-14130

ISPN-14130 Add the memory option in the data Distribution chart

---

cypress/e2e/data-container.cy.js
src/app/Caches/Configuration/DetailConfigurations.tsx
src/app/assets/languages/en.json
src/app/services/cachesHook.ts

https://issues.redhat.com/browse/ISPN-14914

ISPN-14914 Admin view for cache templates

---

src/__tests__/services/downloadServerReport.test.ts
src/app/ClusterStatus/ClusterStatus.tsx
src/app/assets/languages/en.json
src/app/services/clusterHook.ts
src/services/serverService.ts

* Action added to download server report.
* Table changed to TableComposable
* Labels exported
https://issues.redhat.com/browse/ISPN-14230

ISPN-14230 Download server report from cluster membership list

---

cypress/e2e/cache-create-wizard.cy.js
cypress/e2e/rbac_func.cy.js
run-server-for-e2e.sh
src/app/CacheManagers/CacheTableDisplay.tsx
src/app/Caches/Create/CreateCacheWizard.tsx
src/app/Caches/Create/DownloadCacheModal.tsx
src/app/Caches/Create/Features/IndexedCacheConfigurator.tsx
src/app/Caches/Create/ReviewCacheConfig.tsx
src/app/Caches/CreateCache.tsx
src/app/Welcome/Welcome.css
src/app/assets/languages/en.json
src/app/providers/APIAlertProvider.tsx
src/app/routes.tsx
src/app/services/configHook.ts
src/app/utils/dataSerializerUtils.ts
src/services/cacheService.ts
src/types/InfinispanTypes.ts

https://issues.redhat.com/browse/ISPN-14913

ISPN-14913 Create cache configuration

---

src/app/AppLayout/AppLayout.tsx
src/app/Caches/Configuration/CacheConfiguration.tsx
src/app/Caches/Configuration/DetailConfigurations.tsx
src/app/Caches/Create/CacheConfigEditor.tsx
src/app/Caches/Create/Features/PersistentCacheConfigurator.tsx
src/app/Caches/Create/ReviewCacheConfig.tsx
src/app/Caches/DetailCache.tsx
src/app/Caches/Entries/CacheEntries.tsx
src/app/Caches/Query/QueryEntries.tsx
src/app/Common/Health.tsx
src/app/Common/Status.tsx
src/app/ProtoSchema/ProtobufSchemasDisplay.tsx
src/app/Welcome/Welcome.tsx
src/app/index.tsx
src/app/providers/ThemeProvider.tsx
src/app/utils/themeUtils.ts

Changes to add theme switch.
Tested locally
Self checklist (all need to be checked):

ISPN-15105 Console black theme

---

src/app/AppLayout/AppLayout.tsx
src/app/Common/CacheTypeBadge.tsx
src/app/app.css
src/app/assets/languages/en.json
src/app/providers/ThemeProvider.tsx

https://issues.redhat.com/browse/ISPN-15105

ISPN-15105 dark theme fixes

---

src/app/Caches/Configuration/CacheConfiguration.tsx
src/app/Caches/DetailCache.tsx
src/app/Caches/Query/QueryEntries.tsx
src/app/Rebalancing/RebalancingCache.tsx
src/app/XSite/XSiteCache.tsx
src/app/assets/languages/en.json

https://issues.redhat.com/browse/ISPN-15276

 ISPN-15276 simplify header

---

src/app/AccessManagement/AccessManager.tsx
src/app/AccessManagement/FlushRoleCacheModal.tsx
src/app/AppLayout/AppLayout.tsx
src/app/Caches/Configuration/CacheConfiguration.tsx
src/app/Caches/Configuration/DetailConfigurations.tsx
src/app/Caches/Create/CacheConfigEditor.tsx
src/app/Caches/Create/Features/PersistentCacheConfigurator.tsx
src/app/Caches/Create/ReviewCacheConfig.tsx
src/app/Caches/DetailCache.tsx
src/app/Caches/Entries/CacheEntries.tsx
src/app/Caches/Query/QueryEntries.tsx
src/app/Common/Health.tsx
src/app/Common/Status.tsx
src/app/ProtoSchema/ProtobufSchemasDisplay.tsx
src/app/Rebalancing/RebalancingCache.tsx
src/app/assets/languages/en.json
src/app/providers/ThemeProvider.tsx
src/app/services/rolesHook.ts
src/app/utils/themeUtils.ts

one of 3 https://issues.redhat.com/browse/ISPN-15108

ISPN-15108 clean deprecated dropdown

---

src/app/ProtoSchema/CreateProtoSchema.tsx
src/app/ProtoSchema/ProtobufSchemasDisplay.css

Closes: #400 
Added File upload Feature to upload protobuf schema from console.
UI change : 
Tested locally.
User will be able to upload protobuf schema files along with manual text input.
Self checklist (all need to be checked):

ISPN-14054 Add protobuf schema using Upload on the console

---

cypress/e2e/2_cache-detail-search.cy.js
src/app/IndexManagement/IndexManagement.tsx
src/app/IndexManagement/Reindex.tsx
src/app/IndexManagement/UpdateSchema.tsx
src/app/assets/languages/en.json
src/services/searchService.ts

https://issues.redhat.com/browse/ISPN-16482

ISPN-16482 Adds update schema action

---

src/app/CacheManagers/CacheManagers.tsx
src/app/CacheManagers/CacheTableDisplay.tsx
src/app/CacheManagers/CounterTableDisplay.tsx
src/app/Caches/Entries/CacheEntries.tsx
src/app/Common/TableEmptyState.tsx
src/app/IndexManagement/IndexManagement.tsx
src/app/IndexManagement/ViewMetamodel.tsx
src/app/assets/languages/en.json
src/app/services/searchHook.ts
src/services/searchService.ts
src/types/InfinispanTypes.ts

https://issues.redhat.com/browse/ISPN-16490

ISPN-16490 Metamodel index view

---

src/app/CacheManagers/CacheTableDisplay.tsx
src/app/Caches/UpdateAliasCache.tsx
src/app/Common/SelectMultiWithChips.tsx
src/app/assets/languages/en.json
src/app/services/configHook.ts
src/services/cacheService.ts

https://issues.redhat.com/browse/ISPN-16332

ISPN-16332 Add and remove aliases

---

cypress.config.ts
cypress/e2e/1_acess_management.cy.js
cypress/e2e/1_cluster-welcome.cy.js
cypress/e2e/1_data-container.cy.js
cypress/e2e/1_global-stats.cy.js
cypress/e2e/1_rbac_func.cy.js
cypress/e2e/2_cache-detail.cy.js
cypress/e2e/2_cache-tracing.cy.js
cypress/e2e/2_cluster-membership.cy.js
cypress/e2e/3_cache-aliases.cy.js
cypress/e2e/3_cache-crud-wizard.cy.js
cypress/e2e/3_client-connection.cy.js
cypress/e2e/3_proto-schema.cy.js
src/app/AccessManagement/RemovePrincipal.tsx
src/app/ClusterStatus/ClusterStatus.tsx
src/app/GlobalStats/GlobalStats.tsx

Added new Cypress tests.

---

jest.config.js
package-lock.json
package.json
src/services/keycloakService.ts
src/types/InfinispanTypes.ts
tsconfig.json

Update Keycloak 26

---

.github/workflows/pull_requests.yml

actions/upload-artifact@v3 is going to be dismissed in 2025

Bump actions/upload-artifact@4.4.3

---

.github/workflows/pull_requests.yml
cypress.config.ts
cypress/e2e/1_acess_management.cy.js
cypress/e2e/1_cluster-welcome.cy.js
cypress/e2e/1_rbac_func.cy.js
cypress/e2e/2_cache-detail-search.cy.js
cypress/e2e/3_cache-aliases.cy.js
cypress/e2e/4_xsite.cy.js
cypress/e2e/6_cache-bounded-config-edition.cy.js
cypress/e2e/6_cache-indexed-config-edition.cy.js
cypress/e2e/6_cache-secured-config-edition.cy.js
cypress/e2e/7_local-cache-tests.cy.js
cypress/e2e/8_rolling-upgrades-detection.cy.js
cypress/support/commands.js
data/create-data.sh
package.json
restart_server_with_latest_version.sh
run-server-for-e2e-container.sh
scripts/infinispan-local.xml
src/app/Caches/Create/BasicCacheConfigConfigurator.tsx
src/app/Common/SelectMultiWithChips.tsx

Closes: #615 
The PR includes implementation for: 
1. Tests for Local mode;
2. Tests for testing Rolling Upgrades detection
3. A few more tests are added, cleanup stuff added for avoiding random failures, etc.

[#615] Make Cypress tests execution stabel under Firefox and Chrome browsers

---

cypress/e2e/2_cache-detail.cy.js
cypress/e2e/3_cache-crud-wizard.cy.js
src/app/Caches/DetailCache.tsx
src/app/Common/SelectMultiWithChips.tsx
src/app/assets/languages/en.json
src/app/index.tsx
src/services/ConsoleServices.ts

[#629] Add cache delete in cache detail
